### ISSUE TITLE
Can you recomand other good sites to test skills like codility.com?

### ISSUE THREAD

**Issue by ConstantinAlexuta** [jsuchal/codility#1]
Can you recomand other good sites to test skills like codility.com?

**Comment by jsuchal** [comment]
No, not really. I am sorry, I can't help you.

**Comment by atiyil** [comment]
try hackerrank.com

**Comment by ConstantinAlexuta** [comment]
hackerrank.com is awesome. Thanks a lot!
I sow that this one is more for the USA context.
Do you know something similar that is in top for Europe?

**Comment by atiyil** [comment]
Hi Constantin, for Europe codility is the best. I don't know any other unfortunately.
